### ISSUE TITLE
[Bug]:boss bar says []

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#11]
**Describe the bug**it is the normal minecraft one not your new one and all it says is [] yes I’m useing the resource pack it is the wither storm one btw

**Minecraft version**
1.20.1
**Datapack and/or Resource Pack version**
V2.0.3.2
**To Reproduce**

**Screenshots**

**Crash Reports**

**Mod list**
Crackers wither storm mod, crackers wither storm mod plus ,entity model fetures and entity texture features

**Comment by TaintedBlock** [comment]
This usually happens when the resource pack isn't active.

**Comment by Mrtoiletman567** [comment]
It is active and I installed it exactly how you said to

**Comment by TaintedBlock** [comment]
Which version of it did you install? And what phase is the wither storm?

**Comment by Mrtoiletman567** [comment]
The most recent version and on all revived phases

**Comment by TaintedBlock** [comment]
Yeah this just sounds like your resource pack version is outdated. Do you have 5.2?

**Comment by Mrtoiletman567** [comment]
No okay I will see if this does anything don’t close it just yet

**Comment by Mrtoiletman567** [comment]
Thank you so much you fixed it it works!
