### ISSUE TITLE
[Feature]: A little mini game when your making the Formidi-Bomb when You craft it on the surface

### ISSUE THREAD

**Issue by Theonewhodied** [TaintedBlock/crackers-wither-storm-plus#12]
this is kinda will be similar to story mode and instead of grab gunpowder from the air you got to grab it in your inventory because the gunpowder and the super tnt will be randomly moved around you have to grab it and make it on the crafting table with your mouse 

(if you can't make this idea work then if you got a different idea for that then go for it

**Comment by Theonewhodied** [comment]
just to fix this It could be a addon or a setting

**Comment by TaintedBlock** [comment]
This kinda goes out of scope for Plus, and it also seems more annoying than it would be fun.

**Comment by Theonewhodied** [comment]
I know it is thats the point make it more harder and annoying
