### ISSUE TITLE
[Question]:how do I get netherite command block sword

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#14]

**Comment by Mrtoiletman567** [comment]
Oh and also how to make super star sword

**Comment by Mrtoiletman567** [comment]
Like I dropped them on each other on the ground it didn’t do anything

**Comment by TaintedBlock** [comment]
> Like I dropped them on each other on the ground it didn’t do anything

You have to drop them pretty closely together. Almost perfectly

**Comment by TaintedBlock** [comment]
To get netherite command tools, you need a smithing table. I recommend checking out jei and looking through netherite tools uses. The weapon you use also needs to be enchanted, a slight flaw that comes with nbt crafting unfortunately.

**Comment by Mrtoiletman567** [comment]
Is there a mod to get the tools

**Comment by Mrtoiletman567** [comment]
I done what you said the sword didn’t appear

**Comment by TaintedBlock** [comment]
> I done what you said the sword didn’t appear

Try jumping up somewhere and dropping the items right on eachother. Assuming you have all the items needed

**Comment by TaintedBlock** [comment]
> Is there a mod to get the tools

There are other mods, yes

**Comment by TaintedBlock** [comment]
> What mods

I believe "More Command Block Tools" has them. Besides that, I'm not sure of others.

**Comment by Mrtoiletman567** [comment]
I done it all but still nothing

**Comment by Mrtoiletman567** [comment]
Can you just make a crafting table recipe?
