### ISSUE TITLE
[Feature]:can you make a crafting table recipe for the command star sword?

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#16]
**Describe feature you'd like to be added**
I can’t make the sword so I would really like a crafting table recipe I done all the work to get that star and can’t make the sword I wan

**Comment by TaintedBlock** [comment]
The recipe given for the sword is quite simple. I may expand the radius for items to sense so the sword can be created, but a crafting table alternative will not be made.

**Comment by Mrtoiletman567** [comment]
Is there a command to get it?

**Comment by TaintedBlock** [comment]
No, the only way to craft it is with how it is how it is told in the Star Book. The best way to get the sword to craft itself is to drop all the items quickly below you before you pick them up.
