### ISSUE TITLE
[Question]:also I don’t know what order to put the items in to get command star armour

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#18]
I have no idea what to do

**Comment by TaintedBlock** [comment]
You should really install JEI (just enough recipes). Also, you need to obtain the Star Book. Which is only gained from getting the Super Withered Star

**Comment by Mrtoiletman567** [comment]
I installed Jedi it doesn’t show your recipes

**Comment by TaintedBlock** [comment]
> I installed Jedi it doesn’t show your recipes

View the uses of a piece of netherite armor. Read the controls on how to use jei and view recipes as well if you don't know how.
