### ISSUE TITLE
[Feature]:make a withered beacon summon for complete beacon on level four where the command block comes back and teleports around slowly eating blocks too build a new wither storm that’s stronger then the resummoned wither storm please

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#19]
**Describe feature you'd like to be added**
So it should be teleporting every time you get close to it and it uses magic to try and kill you it slowly builds the strongest wither storm yet and it as 3 fights that fail fight one is fighting mobs and trying to survive the command block phase two the wither storm is back use a bow and arrow to Damage the storm but after half health it regents phase 3 you have to kill two withered totems and and three withered symbionts after they die it runs away you have an hour and a half to prepare for the five phased final fight final fight phase one attack the storm and get it to three quarter heath it then grows bigger and gets more hp final fight phase two you have to get a new item called a withered bow and shoot I with that at half heath it enters final fight phase three it spawns 3 withered totems kill them and enter phase four of the final you get it to almost zero hp then the command block falls out of its bowls final fight phase five it continues eating everything attack the command block then it try’s to kill you repeat this 4 times and destroy the command block once and for all and get the mega super withered star

**Comment by TaintedBlock** [comment]
This sounds like a nice idea, but I do not plan on creating or completely remaking a boss fight.

**Comment by Mrtoiletman567** [comment]
Mabye after all the planed updates are done?
