### ISSUE TITLE
[Bug]: Test issue thing I guess

### ISSUE THREAD

**Issue by VillagerN4** [TaintedBlock/crackers-wither-storm-plus#2]
Uhhh, is that supposed to be like that down there?

**Describe the bug**

**Minecraft version**
Tell what Minecraft version you were playing.

**Datapack or Resource Pack? Or both?**
Version of the Resource Pack and/or Datapack you were using.

**To Reproduce**

**Screenshots**

**Crash Reports**
If you crashed, add a crash report so I'm able to try and see how the game crashed.

**Comment by TaintedBlock** [comment]
Nice. Works well. I'm probably gonna edit the template to not look so full.
