### ISSUE TITLE
[Feature]:can you make a wither storm infection?

### ISSUE THREAD

**Issue by Mrtoiletman567** [TaintedBlock/crackers-wither-storm-plus#20]
**Describe feature you'd like to be added**
Blocks quickly become tainted if you use a withered beacon recipe contain a nether star tainted dust tainted flesh and a command block

**Comment by TaintedBlock** [comment]
This feature already exist in the Withered Beacon. With the use of 5 tainted dust, wither rose, chorus fruit, and infected flesh block.

**Comment by Mrtoiletman567** [comment]
What level beacon

**Comment by TaintedBlock** [comment]
> What level beacon

Activated
