### ISSUE TITLE
[Bug: Datapack doesnt work

### ISSUE THREAD

**Issue by DragonCR2011** [TaintedBlock/crackers-wither-storm-plus#21]
Datapack doesnt work even when reloaded, none of the items are obtainable, and the witherstorm isnt respawnable

1.20.1

v2.0.3.2

To Reproduce
1. Load Datapack
2. See bug

Unfortunately, no Screenshots

No Crashes

Mod list:
ColorfulSkies-1.20.1-1.1.2
CraterLib-Forge-1.20-2.1.0
embeddium-0.3.31+mc1.20.1
entity_model_features_forge_1.20.1-2.2.5
entity_texture_features_forge_1.20.1-6.2.4
essential_1-3-4-1_forge_1-20-1
figura-0.1.4+1.20.1-forge-mc
oculus-mc1.20.1-1.7.0
Pehkui-3.8.2+1.20.1-forge
SimpleDiscordLink-Universal-3.1.6
SimpleRPC-Universal-3.3.3
t_en_ms_discs_forge-1.6.0-forge-1.20.1
voicechat-forge-1.20.1-2.5.22
witherstormmod-1.20.1-4.2.1-all

**Comment by TaintedBlock** [comment]
Did you put the datapack in your world folder??

**Comment by DragonCR2011** [comment]
yes

**Comment by TaintedBlock** [comment]
Are you getting the datapack's message when reloading??

**Comment by DragonCR2011** [comment]
yes

**Comment by TaintedBlock** [comment]
> yes

Then the datapack works just fine. If you're looking for the custom items in the creative tab, they cannot be found there and you will have to craft them. 

As for resummoning the storm, you need a fully powered withered beacon. The recipes are given to you via jei when looking at item uses.

**Comment by DragonCR2011** [comment]
thanks! i didnt know that the beackon had to be fully powered!

**Comment by DragonCR2011** [comment]
ok so i can get the items but the storm wont respawn

**Comment by TaintedBlock** [comment]
> ok so i can get the items but the storm wont respawn

Did you look at the JEI recipe?
