### ISSUE TITLE
[Bug]: Datapack doesn't work

### ISSUE THREAD

**Issue by joao-carmassi** [TaintedBlock/crackers-wither-storm-plus#24]
**Describe the bug**
Items and functions of the datapack doesnt word

**Minecraft version**
1.20.1

**Datapack and/or Resource Pack version**
CWSPLUS Datapack 1.20.1 v2.0.3.2
CWSPLUS Resource Pack v5.2

**To Reproduce**
1. donwload evertyhing
2. put the datapack in to the word folde
3. select the datapack
4. run the game
5. and nothin :D

**Screenshots**
![Captura de tela 2024-09-24 171554](https://github.com/user-attachments/assets/760c5d76-ae12-469a-a072-c7cd7547e75e)
![2024-09-24_19 03 38](https://github.com/user-attachments/assets/23bcbc80-55ba-40f0-902f-2886f388a4cb)

**Mod list**
witherstormmod-1.20.1-4.2.1-all.jar
jei-1.20.1-forge-15.8.2.23.jar

**Comment by TaintedBlock** [comment]
I'm not sure as to what you're looking for? For one, datapack items wont show up in the JEI list or creative menu. Their recipes WILL show up however if you click on something that is required to make the item. 

Secondly, assuming you _did_ import everything correctly, the other functions of the pack should work fine.

**Comment by joao-carmassi** [comment]
I did enabled it, I only didn't know that it would only show the itens if I click on something that is required to make the item.
Sorry about that and thank u for the help
