### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by TheoTheGrilo** [TaintedBlock/crackers-wither-storm-plus#26]
**A little bit of a bug and a question**

**1.20.1**

**1.20.1**

JEI (Just enough items) won't show any new crafting recipes, I have searched through articles but I cannot find any crafting recipes on the command block, super star items, or how to use the star book. I have tried using roughly enough items with just your datapack and it crashes. Idk if jei doesn't work because it's a datapack or if it's just broken. Do you have any solutions, or can you at least upload all the crafting recipes to your channel. Because I have no idea on how to obtain the command block in survival and how to use the star book and super withered star. Also by any chance, do you know the command to give the super star and star book, or do I have to fight the re-summoned witherstorm in survival? I hope you are able to respond asap. Thanks!

**Comment by TaintedBlock** [comment]
Firstly, please fill out the template correctly. It helps. 

As for your questions: 
1. JEI wont show the items in the actual list. You'll have to look at the uses of items to see their recipes. This isn't something I cannot fix and is something JEI will have to work on themselves. 

2. There is a wiki here in the github listing these recipes, and the command block recipe can be seen when clicking on it, then clicking on the Withered Beacon icon. If this isn't appearing, there may be something wrong on your end.

3. Both the Star and Star Book are usually obtained after the fight. However, if you use the command:" /loot give @s loot witherstormmod:entities/super_withered_star ", you will be able to obtain it and the book (the book is only obtained through getting the achievement for picking up the star)

**Comment by TheoTheGrilo** [comment]
Thanks, I'll make sure to fill out the template correctly next time
