### ISSUE TITLE
[Bug]: ok it's me Abrar's wither storm from youtube, this is wired. Look this is the problem.                                                                                        **datapck and/**                                  **or resource pack versione**

### ISSUE THREAD

**Issue by abu786786** [TaintedBlock/crackers-wither-storm-plus#27]
**Describe the bug**

**Minecraft version** 1.20.1

**Datapack and/or Resource Pack version** cwsm plus datapack

**To Reproduce**

**Screenshots**

**Crash Reports**
![Screenshot 2024-11-11 212434](https://github.com/user-attachments/assets/13fc8069-c688-4210-b966-23f6463f29c9)
![Screenshot 2024-11-11 212521](https://github.com/user-attachments/assets/aa50789c-013d-4de0-9d70-111c4599f742)

**Mod list** im too lazy to type 
![Screenshot 2024-11-11 212802](https://github.com/user-attachments/assets/53ea7fec-4f64-46d1-827e-e13d842cd65d)
![Screenshot 2024-11-11 212814](https://github.com/user-attachments/assets/5140ef45-c272-4e9a-aa26-96d8145b3858)

**Comment by abu786786** [comment]
=_=

**Comment by abu786786** [comment]
forgot. data is v2.0.4.1

**Comment by TaintedBlock** [comment]
1. That isn't a crash report. Just a screenshot. 
2. Please fill out the report correctly
3. What exactly are you clicking on? You haven't described anything. It looks like you keep clicking on something that's either already on or already off.

**Comment by abu786786** [comment]
oh

**Comment by TaintedBlock** [comment]
Since this was brought up, I did decide to overhaul the config so it tells you how something was changed and if something is already changed.
