### ISSUE TITLE
[Feature]: should you add this? 

### ISSUE THREAD

**Issue by abu786786** [TaintedBlock/crackers-wither-storm-plus#29]
**Describe feature you'd like to be added** ok, me again, can you add, the wither storm when it evolves can you make lightning allover the wither storm?
![Untitled](https://github.com/user-attachments/assets/89d8a1dd-b916-4b22-b2f3-88076e1c73d9)

**Comment by abu786786** [comment]
also new sounds

**Comment by TaintedBlock** [comment]
Interesting idea, but I think evolution is fine personally.
