### ISSUE TITLE
[Bug]: Hello tainted can you fix the the central head of the wither storm it can’t turn 

### ISSUE THREAD

**Issue by Cloudbuster100** [TaintedBlock/crackers-wither-storm-plus#3]
Hello tainted can u please fix the central head of the wither storm it doesn’t turn 

Thanks

**Comment by TaintedBlock** [comment]
It would be better for you to fill out the bug report properly next time. But I won't be fixing this since this is a CWSM issue and not an issue with Plus.

**Comment by TaintedBlock** [comment]
Coming back to this, ended up fixing it and found out it was something else on my part I wasn't aware of before.
