### ISSUE TITLE
[Feature]: Make the bowels flip upside down

### ISSUE THREAD

**Issue by TheoTheGrilo** [TaintedBlock/crackers-wither-storm-plus#30]
**Describe feature you'd like to be added**
Hi me again, so listen. How about during phase three of the bowels fight (when heads activate) The bowels turn upside down, when that happens, a new hole opens up and the command block's platform falls down the hole while the command block its self falls up into the ceiling of the bowels making a small crater, the after you defeat the heads, you can try to pillar up to the command block for the final strike. (as long as your not hit by any phantoms). Or you could just make the bowels flip upside down randomly from time to time. I know this mod isn't made to replicate Minecraft: Story Mode but I just thought it would make the bowels fight more interesting. And, since your kinda finishing up with the bowels fight, I hoped it wouldn't be too late to share my idea. I hope you think about this. I'll be sure to give you more ideas in the future!

**Comment by TaintedBlock** [comment]
Although a cool idea, this is not feasible to do with how CWSM makes the bowels.

(This is now added to the guidelines too)

**Comment by TheoTheGrilo** [comment]
Ok I understand, thanks for responding so quickly

**Comment by himme1358** [comment]
it is possible, just very hard as i know.
