### ISSUE TITLE
[Question]: A lot of questions for the new Datapack v2.1

### ISSUE THREAD

**Issue by TheoTheGrilo** [TaintedBlock/crackers-wither-storm-plus#31]
Sorry for bothering you again, but I have some questions answered in more detailed. (I'm too lazy to test all of these out) 
1. does the new "Infection mode" apply for the resummoned wither storm or both?
2. when you said that mass can spread dimensionally, does that include the end too?
3. Can the wither storm also get mad at you if your in the end?
4. If question 2 is also correct, can the totems spawn in both dimensions? (Nether and end)
5. Can you please explain the "purple diamond" spawner with more detail? Because I don't really understand how this new entity works.
6. Is the witherstorm's Teleport hop ability similar to an Enderman's?
7. do the witherstorm ability's apply to the resummoned or both?
8. In phase 2 of the wither totem, what do you mean by "In 2 minutes, uses the Wither Storm to send a strong beam attack"
9. Can you explain the counter portal-hopper with more detail?
10. when explaining the counter portal-hopper the sentence is cut-off. What was the rest of the sentence?
11. How do you use the command star sword abilities? What is every ability the command star sword has?
12. does the skies raining purple dust and phlegm particles only apply to resummoned or both?
13. Where exactly do you activate the Infection mode?
14. What phase does the witherstorm start getting mad at you in the nether?
15. Can the resummoned witherstorm also get mad at you?

Resource/texture pack questions

16. Is TAW and TAW+ compatible with fresh wither storm+? 
17. Can shaders interfere with the sky colors and stuff in the mod?
18. In TAW+ What phase do enderman start pulling blocks off of the witherstorm?
19. In TAW+ Do enderman pull blocks off the resummoned witherstorm? 

If there is any additional information I should know (more about the infection mode), please let me know! (so I don't bother you a lot) Also if It doesn't waste your time, can you please link some screenshots with your answers to help. Thanks! (sorry for bothering you)

**Comment by TaintedBlock** [comment]
Wow, this is a lot. I will definitely recommend you should actually play the datapack for yourself to find these things out.
But anyway, I'm going to try and make this as short as possible. (Some of these questions can be answered via the config anyway.)

as for your TAW questions: 
16. yes
17. yes, depending on what you use
18. 7.5
19. yes

As for the datapack questions:
1, 5, 11, 12, 13, and 15, can all be answered in game. Whether it be the config, playing the pack in general, or reading tool tips.

2. Yes, I believe so
3. No, it can teleport there
4. yes
6. Not too sure what this means, but no. It just teleports to you after its counter reaches a certain amount
7. Need you to be specific
8. Works exactly as it says
9. Not much to explain. Jump through nether and overworld a bunch to dodge the wither storm, counter goes up, storm teleports
10. Fixed
14. 4 and up

**Comment by TheoTheGrilo** [comment]
I'm still confused with 13. I mean by where in the config can you activate it, because I can't find it. I searched for it but just saw the same stuff I usually would

**Comment by TaintedBlock** [comment]
> I'm still confused with 13. I mean by where in the config can you activate it, because I can't find it. I searched for it but just saw the same stuff I usually would

It's on the 2nd page

**Comment by TheoTheGrilo** [comment]
I clicked on the “W” but I don’t know what to do from there. Can you send a screenshot if possible?

**Comment by TaintedBlock** [comment]
> I clicked on the “W” but I don’t know what to do from there. Can you send a screenshot if possible?

The cwsplus config.. /trigger CONFIG

**Comment by TheoTheGrilo** [comment]
can you give me the whole command, I'm sorry if I sound stupid or smth. I'm just generally confused

**Comment by TaintedBlock** [comment]
> can you give me the whole command, I'm sorry if I sound stupid or smth. I'm just generally confused

That is the whole command. You have to also be in creative

**Comment by TheoTheGrilo** [comment]
is there a way to do it in survival? do I have to mess with the files or smth?

**Comment by TheoTheGrilo** [comment]
also just to be clear, infection mode works on the regular witherstorm right?

**Comment by TheoTheGrilo** [comment]
anyway thanks for the help, sorry for bothering you
