### ISSUE TITLE
[Bug]: Resummoned wither storm laser beam bug  

### ISSUE THREAD

**Issue by TheoTheGrilo** [TaintedBlock/crackers-wither-storm-plus#32]
**Describe the bug**
When fighting the symbionts, sometimes the heads target you. Because It can't pick you up, if you have Tractor tagged enabled, the blocks under you will just get pulled away and you basically get stuck underground. You also get hit by wither skulls too. (Also idk if this is a bug but the wither skull spam gets used way too much.)   

**Minecraft version**
1.20.1

**Datapack and/or Resource Pack version**
CWSPLUS Datapack 1.20.1 v2.1
CWSPLUS Resource Pack v5.4
FRESH CWSPLUS v2.1.6.1
FRESH CWSPLUS - Cwsp Models Detailed v1

**To Reproduce**
1. Resummon the wither storm with the data pack installed  
2. F-bomb with storm and wait 
3. go into survival mode and try to fight the symbionts 
4. If you stay in the fight long enough you'll see you will try to be picked up (and a lot of wither skull spams)

**Mod list**
bettervillage-forge-1.20.1-3.2.0
create-1.20.1-0.5.1.f
createdeco-2.0.2-1.20.1-forge
dungeons-and-taverns-3.0.3.f[Forge]
embeddium-0.3.31+mc1.20.1
entity_model_features_forge_1.20.1-2.2.6
entity_texture_features_forge_1.20.1-6.2.7
jei-1.20.1-forge-15.3.0.7
libraryferret-forge-1.20.1-4.0.0
oculus-mc1.20.1-1.7.0
witherstormmod-1.20.1-4.2.1-all

**Comment by TaintedBlock** [comment]
This is not a bug. This is called an Attack Session. It's intended to be hard to get away from. Hence why you need to be very prepared for the fight. 

Edit: It wont actually be able to pick you up. You just need to stay on the move and be quick.

**Comment by TheoTheGrilo** [comment]
oh thanks, I thought since I wasn't getting picked up meant that it was a bug. Thanks for letting me know
