### ISSUE TITLE
[Bug]: Command star armor stats bug

### ISSUE THREAD

**Issue by KrasiuFierceStudios** [TaintedBlock/crackers-wither-storm-plus#5]
**Describe the bug**
The armor points reset after equipping new command star armor piece. for example: I first equip chestplate which gives me 10 armor points but then I equip the boots after the chestplate my total armor points changes to 6. Basically you only get the armor points of the most recent armor piece equipped (look at the armor bar in the screenshots)
**Minecraft version**
1.20.1
**Datapack and/or Resource Pack version**
v2.0.3.1
**To Reproduce**
1. equip any star armor piece
2. equip another star armor piece
3. see that it only counts the stats of the most recent equipped armor piece

**Screenshots**
![2024-08-21_17 04 15](https://github.com/user-attachments/assets/97227955-0f23-4321-94e7-aad4d89d9140)
![2024-08-21_17 04 50](https://github.com/user-attachments/assets/6442b105-f8cc-4fd7-88f8-f4feabca7387)
![2024-08-21_17 05 02](https://github.com/user-attachments/assets/7eef6182-a896-4929-abc2-aeb704f36d9e)

**Crash Reports**
this bug doesn't cause any crashes

**Comment by TaintedBlock** [comment]
This is certainly strange. Do you have any mods or datapacks that alter armor in some way?

**Comment by KrasiuFierceStudios** [comment]
nope the only mods that I have currently installed only add weapons but no armor

**Comment by TaintedBlock** [comment]
Can you tell me what mods they are?

**Comment by KrasiuFierceStudios** [comment]
the only mods that add content other than cwsm I have in the modpack are spartan weaponry, timeless and classics zero and sophisticated backpacks

**Comment by TaintedBlock** [comment]
Figured out this is a problem with Plus itself. Will be fixed in the next major release.
