### ISSUE TITLE
[Bug]:Wither storm can pick up bedrock after exploding it when summoned with a withered beacon

### ISSUE THREAD

**Issue by Pandaboi25x** [TaintedBlock/crackers-wither-storm-plus#6]
**Describe the bug**
Title

**Minecraft version**
1.20.1

**Datapack and/or Resource Pack version**

**To Reproduce**
1. summon the ws with a withered beacon
2. explode it

**Screenshots**
soon

**Crash Reports**

**Mod list**
![image](https://github.com/user-attachments/assets/bf4debe9-e40e-4641-aa61-b1a6b1d7845d)

**Comment by Pandaboi25x** [comment]
also give me perms to give out labels :)

**Comment by TaintedBlock** [comment]
Will be fixed in the next major release.

**Comment by TaintedBlock** [comment]
> also give me perms to give out labels :)

No
