### ISSUE TITLE
[Bug]: Command Star Armor doesn't give 20 armor points.

### ISSUE THREAD

**Issue by Sn0r3laX** [TaintedBlock/crackers-wither-storm-plus#7]
**Describe the bug**
Command Star Armor doesn't give 20 armor points. If I put the boots and the helmet on, I only get 6 armor points; after that, if I put my chest plate on, I get 10 armor potions. 
**Minecraft version**
1.20.1
**Datapack and/or Resource Pack version**
Datapack: 2.0.3.2 Resource Pack: 5.2
**To Reproduce**
Just put on the command star armor and you'll see it doesn't give you full armor protection
**Screenshots**
![image](https://github.com/user-attachments/assets/1df0e480-e193-4ac4-858e-a09e0fa485e3)
![image](https://github.com/user-attachments/assets/6569a697-22e0-4027-b109-bb3f086702a8)
![image](https://github.com/user-attachments/assets/33d32777-ee86-40c6-a671-fc7284e47cac)

**Crash Reports**

**Mod list**
Only the witherstorm mod and JEI

**Comment by TaintedBlock** [comment]
#5
